spring.application.name=fileupload

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=d78f5c03c16fc3
spring.mail.password=6f1aa6e91d23a6
spring.mail.properties.mail.smtp.auth=PLAIN
